version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install --no-audit
      - run:
          name: lerna-install
          command: npx lerna bootstrap
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: coverage
          command: npm run coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
